
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team02-f23-7pm-4
owner: ucsb-cs156-f23
repo_name: team02-f23-7pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjQxMzg3MDAz","is_bot":false,"login":"audoreven","name":""},"headRefName":"AZhu-UCSBOrgTable-Get","number":60,"title":"AZhu - Add GET specific organization by orgCode","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-4/pull/60"},{"author":{"id":"U_kgDOBm-S5A","is_bot":false,"login":"alicezhong1","name":""},"headRefName":"Alice-MenuItemReview5","number":59,"title":"Alice menu item review5","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-4/pull/59"},{"author":{"id":"U_kgDOBm-S5A","is_bot":false,"login":"alicezhong1","name":""},"headRefName":"Alice-MenuItemReview4","number":57,"title":"Alice menu item review4","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-4/pull/57"},{"author":{"id":"MDQ6VXNlcjc2NDUzODIw","is_bot":false,"login":"EricM5","name":"Eric Marzouk"},"headRefName":"em-UCSBDiningCommonsMenuItem-create-db","number":56,"title":"Create UCSBDiningCommonsMenuItem DB table and Get and POST Controllers + Tests","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-4/pull/56"}]
