
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team02-f23-7pm-4
owner: ucsb-cs156-f23
repo_name: team02-f23-7pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjQxMzg3MDAz","is_bot":false,"login":"audoreven","name":""},"headRefName":"AZhu-UCSBOrgTable","number":46,"title":"audoreven - Add table for UCSB Organizations","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-4/pull/46"},{"author":{"id":"U_kgDOBXhX9g","is_bot":false,"login":"apzhou0","name":""},"headRefName":"Audrey-Articles-add-delete-endpoint","number":45,"title":"azhou - Add DELETE endpoint for a specific record in Articles table.","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-4/pull/45"},{"author":{"id":"U_kgDOBXhX9g","is_bot":false,"login":"apzhou0","name":""},"headRefName":"Audrey-Articles-create-controller","number":44,"title":"Create ArticlesController, add GET (index) and POST (create)","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-4/pull/44"},{"author":{"id":"U_kgDOBXhX9g","is_bot":false,"login":"apzhou0","name":""},"headRefName":"Audrey-Articles-create-db","number":43,"title":"azhou - Created database table for Articles","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-4/pull/43"}]
